"""Password hashing helpers - derive, verify, and grade passwords.

`hash_password(password, method=...)` derives a verifier from a password
and returns a string-encoded hash; `verify_password(stored, candidate)`
checks a candidate password against a previously-stored hash with
constant-time comparison.

Two methods are supported, both stdlib-only:

- `"scrypt"` (default) - RFC 7914. Memory-hard; resistant to GPU/ASIC
  brute-force. Parameters: `n=2**15, r=8, p=1` give ~32 MiB working set.
- `"pbkdf2:sha256"` - NIST SP 800-132. CPU-only; portable to any
  hashlib build (some restricted Python builds lack scrypt).

Stored format: `method$params$salt_b64$hash_b64`. Each segment is
URL-safe base64 without `=` padding for compactness. The method tag at
the front means the verifier can identify which KDF to run on the
candidate even after future additions to this module.

Spec anchors:
- RFC 7914 (scrypt)
- NIST SP 800-132 Sec. 5.3 (PBKDF2)
- OWASP Password Storage cheatsheet
"""

from __future__ import annotations

import asyncio
import hashlib
import hmac
import os
import secrets

from veloce._internal import _b64decode, _b64encode

# Default parameters. Tuned for ~100ms on a 2020-era laptop - enough to
# meaningfully slow offline attack without making login latency painful.
_SCRYPT_N = 2**15  # CPU/memory cost factor
_SCRYPT_R = 8  # block size
_SCRYPT_P = 1  # parallelisation
_SCRYPT_DKLEN = 64
# Minimum acceptable scrypt cost parameters at verify time. Lower than
# the current defaults on purpose: a future tune-up of `_SCRYPT_N`
# (e.g. to 2**17 per the OWASP 2024 recommendation) must not
# retroactively invalidate hashes generated by older Veloce releases.
# Anything below this floor is treated as tampering - N=2 verifies in
# microseconds and turns a database leak into a free-credentials oracle.
_MIN_SCRYPT_N = 2**14
_MIN_SCRYPT_R = 1
_MIN_SCRYPT_P = 1
# Upper bounds mirror the floors: stored hashes whose work factors exceed
# these caps are treated as tampering; the maximum legitimate value is
# bounded by the largest historical Veloce default plus headroom for one
# major-version increase. Without an upper cap an attacker with write
# access to the hash store can set `n=2**30, r=8, p=1` and force the
# verify call to request a multi-terabyte `maxmem` allocation in
# `hashlib.scrypt` - a guaranteed verify-time DoS even if scrypt itself
# eventually refuses to allocate.
_MAX_SCRYPT_N = 2**20  # ~1 GiB at r=8, p=1 - covers OWASP 2030+ projections
_MAX_SCRYPT_R = 32  # default 8; 32x leaves headroom for a future bump
_MAX_SCRYPT_P = 16  # default 1; 16x leaves headroom for a future bump
_MIN_PBKDF2_ITERATIONS = 100_000
# PBKDF2 has no memory cost, only CPU. The cap prevents a tampered hash
# from pinning a verify thread for minutes - 100M iterations is already
# ~100x the current default and well above any realistic OWASP bump path.
_MAX_PBKDF2_ITERATIONS = 100_000_000
# OpenSSL's scrypt enforces `maxmem >= 128 * N * r * p`. Default is 32 MiB,
# which is the exact threshold for the parameters above - give a 2x cushion
# so the call doesn't fail with "memory limit exceeded" on tight builds.
_SCRYPT_MAXMEM = 128 * _SCRYPT_N * _SCRYPT_R * _SCRYPT_P * 2

_PBKDF2_ITERATIONS = 600_000  # OWASP recommendation as of 2023
_PBKDF2_DKLEN = 32

_SALT_BYTES = 16


def hash_password(
    password: str | bytes,
    method: str = "scrypt",
    salt_length: int = _SALT_BYTES,
) -> str:
    """Derive a salted verifier for `password`.

    Returns a self-describing string of the form
    `method$params$salt$hash` where each segment is URL-safe base64
    (no padding). Pass this string verbatim to `verify_password` later.

    `method`:
    - `"scrypt"` (default): RFC 7914, memory-hard.
    - `"pbkdf2:sha256"`: NIST SP 800-132, CPU-only.

    `salt_length` is the number of random bytes used for the salt;
    16 is the OWASP minimum.
    """
    if not password:
        raise ValueError("password must be non-empty")
    if salt_length < 8:
        raise ValueError("salt_length must be >= 8 (OWASP recommendation)")

    if isinstance(password, str):
        password = password.encode("utf-8")
    salt = secrets.token_bytes(salt_length)

    if method == "scrypt":
        derived = hashlib.scrypt(
            password,
            salt=salt,
            n=_SCRYPT_N,
            r=_SCRYPT_R,
            p=_SCRYPT_P,
            dklen=_SCRYPT_DKLEN,
            maxmem=_SCRYPT_MAXMEM,
        )
        params = f"{_SCRYPT_N}:{_SCRYPT_R}:{_SCRYPT_P}"
        return f"scrypt${params}${_b64encode(salt)}${_b64encode(derived)}"

    if method == "pbkdf2:sha256":
        derived = hashlib.pbkdf2_hmac(
            "sha256", password, salt, _PBKDF2_ITERATIONS, dklen=_PBKDF2_DKLEN
        )
        params = str(_PBKDF2_ITERATIONS)
        return f"pbkdf2:sha256${params}${_b64encode(salt)}${_b64encode(derived)}"

    raise ValueError(f"unknown password hashing method: {method!r}")


def _parse_stored(stored: str) -> tuple[str, bytes, bytes] | None:
    """Decode a verifier string into `(method, salt, expected)`.

    Returns None for any structurally invalid input - the same gate
    `verify_password` applies before deciding whether to run a KDF.
    """
    try:
        method, _, salt_b64, hash_b64 = stored.split("$", 3)
        return method, _b64decode(salt_b64), _b64decode(hash_b64)
    except (ValueError, OSError):
        return None


def _scrypt_params(raw: str) -> tuple[int, int, int] | None:
    """Parse and bounds-check stored scrypt `n:r:p`; None if out of range."""
    try:
        n_str, r_str, p_str = raw.split(":")
        n, r, p = int(n_str), int(r_str), int(p_str)
    except ValueError:
        return None
    # Refuse attacker-controlled cost parameters outside the documented
    # window. Below the floor (e.g. `N=2`) a tampered hash verifies in
    # microseconds, defeating scrypt's work floor; above the cap the
    # `maxmem = 128*n*r*p*2` request becomes a verify-time DoS. The floor
    # is hardcoded (not tied to the live `_SCRYPT_N` default) so a future
    # tune-up of the default does not retroactively invalidate legacy
    # hashes.
    if n < _MIN_SCRYPT_N or r < _MIN_SCRYPT_R or p < _MIN_SCRYPT_P:
        return None
    if n > _MAX_SCRYPT_N or r > _MAX_SCRYPT_R or p > _MAX_SCRYPT_P:
        return None
    return n, r, p


def _verifiable(stored: str | None) -> bool:
    """Report whether `stored` is a shape `verify_password` would run a KDF on.

    True means a verify call pays the full KDF cost regardless of match;
    False means it short-circuits before any hashing. `verify_password_or_dummy`
    uses this to decide when to spend decoy work on the no-KDF path.
    """
    if not stored:
        return False
    parsed = _parse_stored(stored)
    if parsed is None:
        return False
    method, _, expected = parsed
    params = stored.split("$", 3)[1]
    if method == "scrypt":
        return len(expected) == _SCRYPT_DKLEN and _scrypt_params(params) is not None
    if method == "pbkdf2:sha256":
        if len(expected) != _PBKDF2_DKLEN:
            return False
        try:
            iterations = int(params)
        except ValueError:
            return False
        return _MIN_PBKDF2_ITERATIONS <= iterations <= _MAX_PBKDF2_ITERATIONS
    return False


def verify_password(stored: str, candidate: str | bytes) -> bool:
    """Compare `candidate` against a `stored` verifier string.

    Returns False (never raises) for any malformed `stored`, unknown
    method, or mismatch. Uses `hmac.compare_digest` for the final byte
    comparison so timing attacks can't leak partial matches.
    """
    if not stored or not candidate:
        return False
    if isinstance(candidate, str):
        candidate = candidate.encode("utf-8")
    parsed = _parse_stored(stored)
    if parsed is None:
        return False
    method, salt, expected = parsed
    params = stored.split("$", 3)[1]

    if method == "scrypt":
        # Reject hashes whose length isn't the canonical derive length -
        # otherwise truncated verifiers would accept the truncated-prefix
        # match of a re-derive at that shorter length.
        if len(expected) != _SCRYPT_DKLEN:
            return False
        cost = _scrypt_params(params)
        if cost is None:
            return False
        n, r, p = cost
        try:
            # Size maxmem based on the stored parameters so verifying a
            # legacy hash with different N/r/p still works.
            maxmem = 128 * n * r * p * 2
            derived = hashlib.scrypt(
                candidate, salt=salt, n=n, r=r, p=p, dklen=_SCRYPT_DKLEN, maxmem=maxmem
            )
        except (ValueError, OSError):
            return False
        return hmac.compare_digest(derived, expected)

    if method == "pbkdf2:sha256":
        if len(expected) != _PBKDF2_DKLEN:
            return False
        try:
            iterations = int(params)
        except ValueError:
            return False
        if iterations < _MIN_PBKDF2_ITERATIONS:
            return False
        if iterations > _MAX_PBKDF2_ITERATIONS:
            return False
        derived = hashlib.pbkdf2_hmac("sha256", candidate, salt, iterations, dklen=_PBKDF2_DKLEN)
        return hmac.compare_digest(derived, expected)

    # Unknown method tag - fail closed.
    return False


# A throwaway verifier derived once, at import, from a random secret using
# the *current* default cost parameters. `verify_password_or_dummy` runs a
# real KDF against this hash on the no-such-hash path so an absent or
# malformed stored verifier costs the same as a genuine wrong-password
# verify (~100 ms). Pinning it to the live defaults means the decoy cost
# tracks any future bump of `_SCRYPT_N`; computing it once keeps the
# enumeration-defence path allocation-free per call.
_DUMMY_HASH = hash_password(secrets.token_bytes(_SALT_BYTES))


def verify_password_or_dummy(stored: str | None, candidate: str | bytes) -> bool:
    """Verify against `stored`, equalising the no-such-hash timing.

    Use this as the login entry point. When `stored` is None, empty, or
    malformed - the shape an attacker probing for valid usernames sees on
    the no-such-user path - a plain `verify_password` would short-circuit
    before any KDF and return in microseconds, while a real wrong-password
    verify costs ~100 ms. That gap leaks which usernames exist. This
    helper runs one real KDF against a cached process-lifetime dummy
    verifier on the no-KDF path so both paths cost the same.

    Returns True only when `stored` is a valid verifier and `candidate`
    matches it; False in every other case.
    """
    if _verifiable(stored):
        # `verify_password` will pay the full KDF cost here whether or not
        # the candidate matches, so the timing is already equalised - no
        # decoy needed. `stored` is non-None given `_verifiable`.
        return verify_password(stored, candidate)  # type: ignore[arg-type]
    # No usable verifier: `verify_password` would have returned in
    # microseconds. Burn an equivalent KDF against the cached dummy so a
    # timing observer cannot distinguish this from a wrong-password verify.
    verify_password(_DUMMY_HASH, candidate)
    return False


async def hash_password_async(
    password: str | bytes,
    method: str = "scrypt",
    salt_length: int = _SALT_BYTES,
) -> str:
    """Async-safe wrapper for `hash_password` - runs the KDF on a thread.

    `hash_password` calls `hashlib.scrypt` / `pbkdf2_hmac` synchronously;
    those are deliberately slow (~100 ms) and would block the event loop
    if called directly from an async handler. This wrapper offloads the
    work to the default executor so the loop stays free for other
    requests. Use this from `async def` handlers; keep the sync
    `hash_password` for sync handlers / scripts / CLI tools.
    """
    return await asyncio.to_thread(hash_password, password, method, salt_length)


async def verify_password_async(stored: str, candidate: str | bytes) -> bool:
    """Async-safe wrapper for `verify_password` - runs the KDF on a thread.

    Same rationale as `hash_password_async`: the scrypt / PBKDF2 verify
    is ~100 ms of CPU; calling it synchronously from an async handler
    blocks the event loop. Offload it.
    """
    return await asyncio.to_thread(verify_password, stored, candidate)


async def verify_password_or_dummy_async(stored: str | None, candidate: str | bytes) -> bool:
    """Async-safe wrapper for `verify_password_or_dummy` - runs on a thread.

    Same rationale as `verify_password_async`, plus the enumeration-defence
    dummy KDF runs off-loop too. Use this as the login entry point from
    `async def` handlers.
    """
    return await asyncio.to_thread(verify_password_or_dummy, stored, candidate)


def is_strong_password(password: str, *, min_length: int = 8) -> bool:
    """Cheap policy check - not exhaustive.

    Returns True only when the password meets a minimum baseline: at
    least `min_length` characters and contains at least one digit AND
    one alphabetic character. Callers that want NIST SP 800-63B-style
    policy (block known-leaked passwords, drop max-length caps, etc.)
    should layer on top.
    """
    if len(password) < min_length:
        return False
    has_alpha = any(c.isalpha() for c in password)
    has_digit = any(c.isdigit() for c in password)
    return has_alpha and has_digit


# Module-level random initialiser sanity check - fail at import if the
# platform has no secure entropy source. `os.urandom` raises NotImplementedError
# on platforms without /dev/urandom; this surfaces the issue earlier
# than the first signup.
_ = os.urandom(1)
